### ISSUE TITLE
command ls ... list only one file

### ISSUE THREAD

**Issue by profra** [zpeters/wmc#1]
I have more files in flash of WiFiMCU but only one (first) is listed.
Your wmc would be very useful... I don't like to have to switch on second machine with Win :-)

**Comment by zpeters** [comment]
I will look into this.  I apologize this is very alpha, have only played with it for a few minutes of testing.  Thank you!

**Comment by zpeters** [comment]
I thought this would have been an easy one but it's going to take some more digging.  Thank you for reporting this, i'll be back in touch soon

**Comment by zpeters** [comment]
I think i've got this working now in the new release.  I've got some new binaries compiled if you want to check it out. I tested uploading and listing multiple files.  Also added a command "read" to print out a file

 I've also added a "cmd" command to run arbitrary commands.  I was able to upload multiple *.lua scripts and run them.  For example

wmc put "flash.lua"
wmc cmd "dofile('flash.lua')"

https://github.com/zpeters/wmc/releases/tag/v0.1.1-alpha

**Comment by profra** [comment]
Thank you for fast response and new functions. I'm at work right now... I will try your new release evening at home... I will give you feedback

**Comment by profra** [comment]
I have tested basic functionality and it seems to be OK.
I have only some notes how to improve the whole CLI:
- handle error conditions (e.g. put, rm without parameters => panic: runtime error
- it was good idea with cmd but very useful would be also simple command run filename
- put and rm commands could work with wildcards (e.g. rm *.lua ...sometimes one needs to make an order in the flash :-),
  or  e.g. put *v2.lua  ... put more files together from project directory into flash)
- also ls command could have some optional flags how to order list of files (e.g. -a ascending, -d descending)
- please try this simple program

```
-----------------------
--gpio demo
print("------gpio demo------")
print("Test gpio output function")
print("Set gpio 17 as output")
print("gpio 17 connect to LED on WiFiMCU board")
gpio.mode(17,gpio.OUTPUT)
local i=0
repeat 
    print("Light on LED")
    gpio.write(17,gpio.LOW)
    tmr.delayms(500)
    print("Light off LED")
    gpio.write(17,gpio.HIGH)
    tmr.delayms(500)
    i = i+1
until i>10
-----------------------
```

... output of all prints is going to screen ONLY in the moment when the program is finished...
I think (if the terminal should be an output console) that every print should go to the screen immediately...
BUT I don't know if it was your intention that the terminal screen is also output console for running program.

Thank you very much for your work on this CLI for WiFiMCU, it will be very handy tool for all people tinkering with it.
... AND on the end the whole set of commands could have some environment in JS or Java  when you build it for more platforms :-)

**Comment by zpeters** [comment]
Thank you so much for the feedback.  I will  close this issue but i will take your comments and create new issues.  I think all of the suggestions are worth looking into.

Have fun!
